<a href="https://colab.research.google.com/github/metsumesquita/Python_resumo/blob/main/vetor%2Ctuplas_e_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vetores
[*array*](https://numpy.org/doc/stable/user/basics.creation.html)

[index](https://thispointer.com/find-the-index-of-a-value-in-numpy-array/)

o array é mutavel e seus items sao do mesmo tipo de dado sempre

In [ ]:
a = np.array([2, 3, 4, 5, 6,10,15, 45, 67, 34])

In [ ]:
a.size

In [ ]:
result = np.where(a == 15)
print('retorno do array e posiçao : ', result)
print("retornando a possiçao onde o elemento de valor 15 é encontrato ", result[0], sep='\n')

In [ ]:
#cria um vetor que cresce regularmente /
np.arange(10)

In [ ]:
#numpy.linspace criará arrays com um número especificado de elementos
#e espaçado igualmente entre os valores inicial e final especificados.
np.linspace(0., 8., 6)

In [ ]:
#array de duas dimensoes
a2D = np.array([[1, 2], [3, 4]])

In [ ]:
#esse exemplo é uma matriz identidade
#onde quando i=j sera igual a 1(linha coluna)
np.eye(4, 4)

In [ ]:
a = np.array([10,11,12,13,14,15,16,17,18,,19,20])
print(arr)

In [ ]:

import numpy as np

# create numpy array elements
a = np.array([2, 3, 4, 5, 6, 45, 67, 34])

# display element index where value = 45

index_of_element = -1
for i in range(a.size):
    if a[i] == 45:
        index_of_element = i
        break

if index_of_element != -1:
    print("element index  : ", index_of_element)
else:
    print("The element not present")

In [ ]:
#podemos tranforma uma lista em um array
list_number=[3,5,4,2,1,5,6,7,3]

#aqui é feito um cast
array_1d=np.array(list_number)
type(arr)

In [ ]:
def valores_faltantes(nums):
    nums = sorted(set(nums))  # remove duplicatas e ordena
    faltando = []
    for i in range(nums[0], nums[-1]):
        if i not in nums:
            faltando.append(i)
    return faltando
lista = [10, 11, 13, 14, 16, 20]
print(valores_faltantes(lista))

[12, 15, 17, 18, 19]


#Tuples ou tuplas


---
######Imutáveis: Uma vez criadas, as tuplas não podem ser alteradas. Isso significa que você não pode adicionar, remover ou modificar elementos dentro de uma tupla.
######Tipos de Dados: Podem armazenar diferentes tipos de dados na mesma coleção (por exemplo, uma tupla pode conter um número, uma string e uma lista).
#####Métodos: As tuplas têm menos métodos disponíveis em comparação com listas. Por exemplo, não têm métodos como append ou remove porque não podem ser modificadas.
#####Troca de Valores: Um exemplo clássico de uso de tuplas é a troca de valores entre variáveis. Isso é feito de maneira elegante e simples com tuplas, assim: a, b = b, a.

In [ ]:
a = [1, 4, 3]
b = [3, 2, 2]

def store_original_ids():
    a = [1, 4, 3]
    b = [3, 2, 2]

store_original_ids()
#aqui tempos um SWAP
temp =b
b=a
a=temp
#que tambem poderia ser resolvido assim

##a, b = a, b

def check():
     if a==[3, 2, 2] and b ==[1, 4, 3] :
            print('certo')

check()

In [ ]:
Estados = namedtuple('Estados', ['sigla', 'nome'])
estado_pe = Estados('PE', 'Recife')
estado_pe

In [ ]:
Estados(sigla='PE', nome='recife')
print(estado_pe.sigla)
print(estado_pe.nome)

In [ ]:
#devemos  usar uma 3 variavel para fazer o wap funcionar corretamente
#caso contrario um dos valores das variaveis sera perdido
#observe abaixo:
coordenada_xy = (10, 20)
x, y = coordenada_xy
temp=x   # 10
x=y      # 20
y=temp   # 10
#portanto usamos a variavel temp para armazena o valor de x antes dele ser modificado/substituido por um novo valor
print("valor de variavel  x : "+str(x)+   "\n"
     +"valor de variavel  y : "+ str(y) + "\n"
    + "valor de variavel temp : "+ str(temp))
#para usar esses valores que conhecemos precisamos colocar eles como se fossem string

In [ ]:
# Swap com tuplas.
print("x e y antes do swap: ", x, y)

x, y = y, x

print("x e y depois do swap: ", x, y)

In [ ]:
tupla_nomes = ('Giordano', 'Paulo', 'Lucas', 'João', 'Felipe')
#se o elemento esta na tupla
print('Giordano' in tupla_nomes)

print('Paulo' in tupla_nomes)

print (tupla_nomes.count('Lucas')) #< possui unica vez o nome lucas

print(tupla_nomes.index("João"))# retorna a posiçao na tupla

In [ ]:
# tupla com apenas um elemento
#nao precisa usar sempre ()
tupla_elemento = 10,
tupla_elemento

In [ ]:
nick=("n","i","n","a")

nick.index("n")#retorna a vez q aparece primeiro

In [ ]:
name_1=("m","a","r","i","a","n","a")

print(name_1.index("n"))#retorna a vez q aparece primeiro

print(name_1.index("a"))

#matrizes

In [ ]:
import numpy as np

# uma matriz de 3 d
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [ ]:
import numpy as np
#aqui uma matrix de 3d
matrix=[[11,12,13],[21,22,23],[31,32,33]]
array_3D=np.array(matrix)
print(array_3D)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D[0])

[[1 2]
 [3 4]]


In [ ]:
print(a3D[1])

[[5 6]
 [7 8]]


In [ ]:
#retorma o numero de dimensoes de um array
print(a3D.ndim)

3
